model:
  _target_ : slfm.model.FlowNeuralNetwork
  n_features: 2
  time_embedding_size: 8 
  n_blocks: 5
  
trainer:
  max_epochs: 300
  log_interval: 1
  loss: 
    _target_: slfm.loss.ConditionalFlowMatchingLoss 
  optimizer:
    _target_: torch.optim.AdamW
    lr: 0.1           # Learning rate
    weight_decay: 0.0001  # Weight decay (L2 regularization)
  
data:
  _target_: slfm.datasets.DatasetCreator
  size: 10000

logger:
  _target_: slfm.logger.Logger
  log_dir: logs/flow_fc_${model.n_features}_${model.time_embedding_size}_${model.n_blocks}
  loss_dir: loss
  ckpt_dir: ckpt 
  visuals_dir: visuals
  