model:
  _target_ : slfm.model.FlowMLP
  n_features: 2
  width: 10
  n_blocks: 5
  input_mult: 1
  output_mult: 1
  
mup: 
  switch: True
  save_base_shapes: width_10.bsh
  coord_check_filename: coord_check_mup_10.png

trainer:
  max_epochs: 500
  log_interval: 10
  loss: 
    _target_: slfm.loss.ConditionalFlowMatchingLoss 
  optimizer:
    _target_: torch.optim.AdamW # mup.MuAdam
    lr: 0.1           # Learning rate
    weight_decay: 0.001  # Weight decay (L2 regularization)
    lr_scheduler: linear_decay
    gradient_clip: 1.0

data:
  _target_: slfm.datasets.CustomDataset # slfm.datasets.DatasetCreator
  size: 10000

logger:
  _target_: slfm.logger.Logger
  log_dir: logs/flow_mup_fc_w${model.width}_lr${trainer.optimizer.lr}
  loss_dir: loss
  ckpt_dir: ckpt 
  visuals_dir: visuals
  